FROM python:3.6-alpine
COPY . /app
WORKDIR /app
RUN apk add --no-cache --virtual .build-deps gcc python3-dev linux-headers musl-dev mercurial git
RUN apk add tzdata
RUN pip install -r requirements.txt
CMD ["python", "main.py"]
