version: '2'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VER: '1.7.5.3'
        SMTP_ENABLED: 'true'
        SMTP_HOSTNAME: 'smtp.gmail.com'
        SMTP_PORT: 587
        SMTP_AUTH: 'false'
        SMTP_USERNAME: 
        SMTP_PASSWORD:
        XNAT_DATASOURCE_DIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
        XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
        TOMCAT_XNAT_FOLDER: ROOT
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    ports:
      - "8081:8080"
      - "8000:8000"
      - "8104:8104"
      - "8105:8105"
    volumes:      
      - /data/shared/temp/xnat/home/logs:/data/xnat/home/logs
      - /data/shared/temp/xnat/home/plugins:/data/xnat/home/plugins
      - /data/shared/temp/xnat/archive:/data/xnat/archive
      - /data/shared/temp/xnat/prearchive:/data/xnat/prearchive
      - /data/shared.temp/xnat/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx1024m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - XNAT_HOME=/data/xnat/home
    extra_hosts:
      - "xnat.monash.edu:115.146.84.154"

  xnat-db:
    build: ./postgres
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  xnat-nginx:
    build: ./nginx
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - xnat-web

  xnat-hasher:
    build: ./hasher
    ports:
      - "127.0.0.1:8888:8888"
    volumes:      
      - /data/xnat/home/logs:/data/xnat/home/logs
    expose:
      - "8888"
    links:
      - xnat-web
      - xnat-db
      
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #   command:
  #     - '-config.file=/etc/prometheus/prometheus.yaml'
  #   ports:
  #     - '9090:9090'
  #   links:
  #     - cadvisor
  #
  # cadvisor:
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - "8082:8080"
  #   expose:
  #     - 8082
